name: "addonfactory-test-matrix-action"
description: "This tool automates the selection matrix dimensions"
inputs:
  features:
    description: 'Comma separated list of features.'
    required: false
    type: string
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --features
    - ${{ inputs.features }}
