[GENERAL]
LATEST = 10.2
OLDEST = 9.3

[10.2]
VERSION = 10.2.1
BUILD = c892b66d163d
SUPPORTED = 2028-01-15
PYTHON39 = true
PYTHON37 = false

[10.0]
VERSION = 10.0.4
BUILD = 5ea723e837ec
SUPPORTED = 2027-07-28
PYTHON39 = true
PYTHON37 = false

[9.4]
VERSION = 9.4.9
BUILD = 03bb451d4e07
SUPPORTED = 2026-12-16
PYTHON39 = true
PYTHON37 = false

[9.3]
VERSION = 9.3.10
BUILD = ec8fc22ae0e4
SUPPORTED = 2026-07-24
PYTHON39 = true
PYTHON37 = false


