[GENERAL]
LATEST = 10.4
OLDEST = 9.4

[10.2]
VERSION = 10.2.7
BUILD = c0bff5b0fac3
SUPPORTED = 2028-01-15
PYTHON39 = true
PYTHON37 = false

[10.0]
VERSION = 10.0.10
BUILD = c66ca3846eb8
SUPPORTED = 2027-07-28
PYTHON39 = true
PYTHON37 = false
SERVER_CONF_PYTHON_VERSIONS = python3,force_python3

[9.4]
VERSION = 9.4.15
BUILD = ae018c4ea857
SUPPORTED = 2026-12-16
PYTHON39 = true
PYTHON37 = false
SERVER_CONF_PYTHON_VERSIONS = python3,force_python3

[10.4]
VERSION = 10.4.3
BUILD = 4174a2deda5d
SUPPORTED = 2028-05-18
PYTHON39 = true
PYTHON37 = false

